### ISSUE TITLE
what's mean "Unexpected instance batch specified for instance batch" error message

### ISSUE THREAD

**Issue by kimkanghyune** [vagran/dxf-viewer#21]
[example](https://cadview-media.connectforyouserver.net/housedesign.dxf)

I was testing the example above.
Then I got an error message.

I'd like to ask what issues in the drawing need to be addressed and if they can be forced to hand over.

**Comment by vagran** [comment]
This is internal assertion which should never happen. It indicates some internal bug in the viewer. However I cannot reproduce this issue with your example on the [deployed demo](https://vagran.github.io/dxf-viewer-example/). Most likely it might be caused either by some of your changes in the dxf-viewer code (if any) or somehow introduced inconsistency in its run-time state (sometimes this might happen if using various hot-reload features in web dev tools like webpack or vite, page refresh usually fixes the problem in such case).
If the problem is permanently reproducible with the repository version of the package, then I need more information to reproduce it.

**Comment by kimkanghyune** [comment]
This error occurred because the versions did not match. It was a problem with the source code that I arbitrarily modified.
thank you.
