### ISSUE TITLE
Some entities not rendered

### ISSUE THREAD

**Issue by AsiaMartini** [vagran/dxf-viewer#5]
When I try to load the same file in your deployed demo and in my project (not Vue), results are different.
This is the result of your deployed demo:

![image](https://user-images.githubusercontent.com/69966660/135228213-ac861e27-9428-4771-a314-59065a404bac.png)

This is my project output (as you can see, some entities are missing):

![image](https://user-images.githubusercontent.com/69966660/135228171-842c6816-ee6c-4b5a-864f-edd32179b961.png)

What could I have done wrong?
I see no errors in console.
Thanks.

**Comment by vagran** [comment]
It is quite difficult to say what can be a problem just by these pictures. Vue itself does not add anything to the rendering, it was used just to illustrate how to use the library with some popular framework.

**Comment by Leessonomy** [comment]
I have a similar problem. @vagran 
This is the only problem because of which I'm wary of using your library

Thanks

![test1](https://user-images.githubusercontent.com/45308678/142641027-d7078a23-421f-4e74-821b-f03336c8cbd4.png)
![test2](https://user-images.githubusercontent.com/45308678/142641055-29e79fc2-2a1b-4ebc-9a8f-32b33a471191.png)

**Comment by vagran** [comment]
As I see you have a problem with multiline text and some solids (probably 3DFACE or 3DSOLID entities). Both are not implemented as stated in the repository readme. However, MTEXT is definitely the most important feature to implement next, so it the first position in my TODO list. There is probably no way for 3DSOLID since it has some proprietary data inside. 3DFACE should be quite simple but seems not to be so important because this viewer is designed as 2D only. But I still have this in my roadmap, and will try to find some time to implement both MTEXT and 3DFACE entities support.

**Comment by vagran** [comment]
I have just implemented limited support for MTEXT entity. So at least multiline text should appear now in this test file.
@Leessonomy Is it possible to get your test file?

**Comment by Leessonomy** [comment]
@vagran sure https://ru.files.fm/u/su94k8t7f

**Comment by vagran** [comment]
Thanks. Multiline text is now rendered. I do not see points for some reason, however they are fully supported (including various styles via [$PDMODE](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-82F9BB52-D026-4D6A-ABA6-BF29641F459B-htm.html) variable). I'll check it later.
Solids are not displayed because SOLID group is not yet supported but I'll also implement this soon among with 3DFACE support.

![image](https://user-images.githubusercontent.com/6065976/143427131-5f5b6773-e1a9-4300-a198-6ee6ae044cac.png)

**Comment by vagran** [comment]
I have added support for SOLID and 3DFACE. Also fixed problem with points rendering. Now the picture seems to be fully correct. @Leessonomy please also note that your reference picture has some problems: multiline text is not properly aligned (`pxqc;` not handled), and blocks are not properly colored. I verified it with the Autodesk online viewer.
![image](https://user-images.githubusercontent.com/6065976/143621073-6ac17897-f718-43c3-a096-07c0b00b1bc8.png)
