### ISSUE TITLE
Some Questions about the Parameters in the TextDecoder() Method

### ISSUE THREAD

**Issue by NightMoom** [vagran/dxf-viewer#72]
in `DxfFetcher.js`
class TextDecoder() use params `gbk`

```js
 //... other code
 let buffer = ""
 let decoder = new TextDecoder("utf-8")
``` 

then can not resolve Chinese 

![20230704144714](https://github.com/vagran/dxf-viewer/assets/29970730/700d449e-8e2d-4d92-8d0e-4f1aca8ba62b)

I see this docs [nodejs for textdecoder](https://nodejs.org/api/util.html#class-utiltextdecoder)

i find has same params like `gbk` 

```javascript
 let decoder = new TextDecoder("gbk")
```

![20230704145846](https://github.com/vagran/dxf-viewer/assets/29970730/fec9deab-2b10-4705-a672-5c962802a216)

Can we consider making the encoding an optional parameter？

example：

```javascript
export class DxfFetcher {
     constructor(url, decoder = 'utf-8') {
        this.url = url
        this.decoder = decoder
    }

   async Fetch(processCbk = null) {
     // .... other code
     let decoder = new TextDecoder(this.decoder)
     // .... other code
   }
}
```

**Comment by vagran** [comment]
Yes, we can probably do this. Actually, all newer files (starting from R2007) should be 'utf-8' encoded. For older files, there is a header variable `$DWGCODEPAGE` which sets the proper encoding. Problem is that we initialize decoder before parsing the file. May be it is worth to remake parsing, implementing deferred text fields decoding, after overall structure is parsed. The simplest approach with UTF-8 assumption is used now because I am unaware how common are that old files in the wild. BTW can you confirm that your file has `gbk` value in `$DWGCODEPAGE` variable?

**Comment by NightMoom** [comment]
in header has $DWGCODEPAGE: 'gb_2312'

**Comment by vagran** [comment]
> in header has $DWGCODEPAGE: 'gb_2312'
Ok, thanks. It seems that it also requires some mapping from possible values in this variable to a set of encodings supported by JavaScript.
For now I will proceed with propagating this parameter to the viewer options.

**Comment by vagran** [comment]
> It seems that it also requires some mapping from possible values in this variable to a set of encodings supported by JavaScript.

Just checked, my browser JS also supports `gb_2312` as alias for `gbk`. Not sure if it is cross-browser behavior since it is [not documented](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/encoding).

**Comment by vagran** [comment]
I have added `fileEncoding` option.
